// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: replik.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Replik_GetStatus_FullMethodName   = "/api.Replik/GetStatus"
	Replik_GetFileList_FullMethodName = "/api.Replik/GetFileList"
	Replik_GetFile_FullMethodName     = "/api.Replik/GetFile"
)

// ReplikClient is the client API for Replik service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReplikClient interface {
	GetStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Status, error)
	GetFileList(ctx context.Context, in *FileListRequest, opts ...grpc.CallOption) (*FileList, error)
	GetFile(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (Replik_GetFileClient, error)
}

type replikClient struct {
	cc grpc.ClientConnInterface
}

func NewReplikClient(cc grpc.ClientConnInterface) ReplikClient {
	return &replikClient{cc}
}

func (c *replikClient) GetStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, Replik_GetStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replikClient) GetFileList(ctx context.Context, in *FileListRequest, opts ...grpc.CallOption) (*FileList, error) {
	out := new(FileList)
	err := c.cc.Invoke(ctx, Replik_GetFileList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replikClient) GetFile(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (Replik_GetFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &Replik_ServiceDesc.Streams[0], Replik_GetFile_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &replikGetFileClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Replik_GetFileClient interface {
	Recv() (*Chunk, error)
	grpc.ClientStream
}

type replikGetFileClient struct {
	grpc.ClientStream
}

func (x *replikGetFileClient) Recv() (*Chunk, error) {
	m := new(Chunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ReplikServer is the server API for Replik service.
// All implementations must embed UnimplementedReplikServer
// for forward compatibility
type ReplikServer interface {
	GetStatus(context.Context, *Empty) (*Status, error)
	GetFileList(context.Context, *FileListRequest) (*FileList, error)
	GetFile(*FileRequest, Replik_GetFileServer) error
	mustEmbedUnimplementedReplikServer()
}

// UnimplementedReplikServer must be embedded to have forward compatible implementations.
type UnimplementedReplikServer struct {
}

func (UnimplementedReplikServer) GetStatus(context.Context, *Empty) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedReplikServer) GetFileList(context.Context, *FileListRequest) (*FileList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFileList not implemented")
}
func (UnimplementedReplikServer) GetFile(*FileRequest, Replik_GetFileServer) error {
	return status.Errorf(codes.Unimplemented, "method GetFile not implemented")
}
func (UnimplementedReplikServer) mustEmbedUnimplementedReplikServer() {}

// UnsafeReplikServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReplikServer will
// result in compilation errors.
type UnsafeReplikServer interface {
	mustEmbedUnimplementedReplikServer()
}

func RegisterReplikServer(s grpc.ServiceRegistrar, srv ReplikServer) {
	s.RegisterService(&Replik_ServiceDesc, srv)
}

func _Replik_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplikServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Replik_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplikServer).GetStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Replik_GetFileList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplikServer).GetFileList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Replik_GetFileList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplikServer).GetFileList(ctx, req.(*FileListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Replik_GetFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ReplikServer).GetFile(m, &replikGetFileServer{stream})
}

type Replik_GetFileServer interface {
	Send(*Chunk) error
	grpc.ServerStream
}

type replikGetFileServer struct {
	grpc.ServerStream
}

func (x *replikGetFileServer) Send(m *Chunk) error {
	return x.ServerStream.SendMsg(m)
}

// Replik_ServiceDesc is the grpc.ServiceDesc for Replik service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Replik_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.Replik",
	HandlerType: (*ReplikServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _Replik_GetStatus_Handler,
		},
		{
			MethodName: "GetFileList",
			Handler:    _Replik_GetFileList_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetFile",
			Handler:       _Replik_GetFile_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "replik.proto",
}
